/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppendMessageRequest {
  'kind' : MessageKind,
  'conversationId' : ConversationId,
}
export interface Conversation {
  'id' : ConversationId,
  'title' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type ConversationId = bigint;
export interface ConversationPreview {
  'id' : ConversationId,
  'title' : string,
  'snippet' : string,
  'updatedAt' : Timestamp,
}
export interface CreateConversationRequest { 'title' : string }
export type ExternalBlob = Uint8Array;
export interface FileAttachmentMeta {
  'blob' : ExternalBlob,
  'mimeType' : string,
  'filename' : string,
}
export interface ImageGenRequest {
  'conversationId' : ConversationId,
  'prompt' : string,
}
export interface ImageGenResponse {
  'rawJson' : string,
  'messageId' : MessageId,
}
export interface ListConversationsRequest {
  'offset' : bigint,
  'limit' : bigint,
}
export interface ListConversationsResponse {
  'total' : bigint,
  'conversations' : Array<ConversationPreview>,
}
export interface Message {
  'id' : MessageId,
  'kind' : MessageKind,
  'createdAt' : Timestamp,
  'conversationId' : ConversationId,
}
export type MessageId = bigint;
export type MessageKind = { 'aiImage' : ExternalBlob } |
  { 'userText' : string } |
  { 'aiText' : string } |
  { 'fileAttachment' : FileAttachmentMeta };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'appendMessage' : ActorMethod<[AppendMessageRequest], Message>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createConversation' : ActorMethod<[CreateConversationRequest], Conversation>,
  'deleteConversation' : ActorMethod<[ConversationId], boolean>,
  'generateImage' : ActorMethod<[ImageGenRequest], ImageGenResponse>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[ConversationId], Array<Message>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listConversations' : ActorMethod<
    [ListConversationsRequest],
    ListConversationsResponse
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformChat' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];