/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileAttachmentMeta = IDL.Record({
  'blob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const MessageKind = IDL.Variant({
  'aiImage' : ExternalBlob,
  'userText' : IDL.Text,
  'aiText' : IDL.Text,
  'fileAttachment' : FileAttachmentMeta,
});
export const ConversationId = IDL.Nat;
export const AppendMessageRequest = IDL.Record({
  'kind' : MessageKind,
  'conversationId' : ConversationId,
});
export const MessageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'kind' : MessageKind,
  'createdAt' : Timestamp,
  'conversationId' : ConversationId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateConversationRequest = IDL.Record({ 'title' : IDL.Text });
export const UserId = IDL.Principal;
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const ImageGenRequest = IDL.Record({
  'conversationId' : ConversationId,
  'prompt' : IDL.Text,
});
export const ImageGenResponse = IDL.Record({
  'rawJson' : IDL.Text,
  'messageId' : MessageId,
});
export const ListConversationsRequest = IDL.Record({
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
});
export const ConversationPreview = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'snippet' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const ListConversationsResponse = IDL.Record({
  'total' : IDL.Nat,
  'conversations' : IDL.Vec(ConversationPreview),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'appendMessage' : IDL.Func([AppendMessageRequest], [Message], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func(
      [CreateConversationRequest],
      [Conversation],
      [],
    ),
  'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
  'generateImage' : IDL.Func([ImageGenRequest], [ImageGenResponse], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listConversations' : IDL.Func(
      [ListConversationsRequest],
      [ListConversationsResponse],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformChat' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileAttachmentMeta = IDL.Record({
    'blob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const MessageKind = IDL.Variant({
    'aiImage' : ExternalBlob,
    'userText' : IDL.Text,
    'aiText' : IDL.Text,
    'fileAttachment' : FileAttachmentMeta,
  });
  const ConversationId = IDL.Nat;
  const AppendMessageRequest = IDL.Record({
    'kind' : MessageKind,
    'conversationId' : ConversationId,
  });
  const MessageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'kind' : MessageKind,
    'createdAt' : Timestamp,
    'conversationId' : ConversationId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateConversationRequest = IDL.Record({ 'title' : IDL.Text });
  const UserId = IDL.Principal;
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const ImageGenRequest = IDL.Record({
    'conversationId' : ConversationId,
    'prompt' : IDL.Text,
  });
  const ImageGenResponse = IDL.Record({
    'rawJson' : IDL.Text,
    'messageId' : MessageId,
  });
  const ListConversationsRequest = IDL.Record({
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
  });
  const ConversationPreview = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'snippet' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const ListConversationsResponse = IDL.Record({
    'total' : IDL.Nat,
    'conversations' : IDL.Vec(ConversationPreview),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'appendMessage' : IDL.Func([AppendMessageRequest], [Message], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func(
        [CreateConversationRequest],
        [Conversation],
        [],
      ),
    'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
    'generateImage' : IDL.Func([ImageGenRequest], [ImageGenResponse], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listConversations' : IDL.Func(
        [ListConversationsRequest],
        [ListConversationsResponse],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformChat' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };